### ISSUE TITLE
formatter不支持

### ISSUE THREAD

**Issue by QQ853695231** [chenbinli-dev/echarts-ssr#1]
把echarts的option传到对应接口后，发现legend里面的formatter没有渲染出来

**Comment by aloniacode** [comment]
> 把echarts的option传到对应接口后，发现legend里面的formatter没有渲染出来

![image](https://github.com/user-attachments/assets/eb150b62-5902-427b-8c50-a16919ff32bc)
函数依旧是使用字符串形式来传
